wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    code_path: code/baselines_train.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.1
    start_time: 1672173105.828891
    t:
      1:
      - 1
      - 3
      - 55
      3:
      - 13
      - 16
      - 23
      - 35
      4: 3.9.1
      5: 0.13.5
      8:
      - 3
      - 5
adversaries:
  desc: null
  value: jules
batch_size:
  desc: null
  value: 128
clip_range:
  desc: null
  value: 0.2
current_round:
  desc: null
  value: 2
ent_coef:
  desc: null
  value: 0.2
env_name:
  desc: null
  value: MagicMan-v0
gae_lambda:
  desc: null
  value: 0.95
gamma:
  desc: null
  value: 0.99
learning_rate:
  desc: null
  value: __main__.linear_schedule.<locals>.func
n_epochs:
  desc: null
  value: 10
normalize_advantage:
  desc: null
  value: false
policy_kwargs:
  desc: null
  value:
    activation_fn: torch.nn.modules.activation.ReLU
    net_arch:
    - pi:
      - 64
      - 64
      vf:
      - 64
      - 64
policy_type:
  desc: null
  value: MlpPolicy
total_timesteps:
  desc: null
  value: 1000000
vf_coef:
  desc: null
  value: 0.5
